package game;

/**
 * Created by xlo on 2016/1/4.
 * it's the game state
 */
public enum GameState {
    BEFORE_GAME_START, WHEN_GAME_START, AFTER_GAME_START, BEFORE_ROUND_START, WHEN_ROUND_START, AFTER_ROUND_START,
    BEFORE_DAY_TIME, WHEN_DAY_TIME, AFTER_DAY_TIME, BEFORE_NIGHT, WHEN_NIGHT, AFTER_NIGHT,
    BEFORE_ROUND_END, WHEN_ROUND_END, AFTER_ROUND_END, BEFORE_GAME_END, WHEN_GAME_END, AFTER_GAME_END
}
